# Generated by Django 3.1.7 on 2021-03-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_confirm',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da Confirmação'),
        ),
    ]
